Repository Mbiydzenyuy3/ChessMeet, pull requests merged in 2025-09, with the labels that each got.

#21 Feature/game vs ai
  .gitignore
  app/main/_layout.tsx
  app/main/game.tsx
  app/main/index.tsx
  components/AssistantPanel.tsx
  components/GameHeader.tsx
  components/MoveList.tsx
  components/UI.tsx
  hooks/useSocket.ts
  store/gameSlice.ts
  types/interface.ts
Labels: ui-ux-improvement, component-architecture

#25 Feat/profile
  app/main/_layout.tsx
  app/main/index.tsx
  app/settings/SettingsScreen.tsx
  components/AssistantPanel.tsx
  components/FloatingPiece.tsx
  components/MoveList.tsx
  components/TransitionScreen.tsx
  constants/colors.ts
Labels: ui-ux-improvement, component-architecture

#32 fix change
  app/main/game.tsx
  app/main/index.tsx
Labels: ui-ux-improvement, component-architecture

#33 Feat/app
  app/auth/OTPverify.tsx
  app/main/_layout.tsx
  app/main/game.tsx
  app/settings/SettingsScreen.tsx
Labels: ui-ux-improvement, component-architecture, accessibility-enhancement, responsive-design

#34 implemnted the online moden
  app/main/game.tsx
  app/main/index.tsx
  app/main/machmakin.tsx
  types/navigation.ts
Labels: ui-ux-improvement, component-architecture

#38 Feature/update front
  app/main/.game.tsx.swp
  app/main/_layout.tsx
  app/main/game.tsx
  app/main/index.tsx
  app/main/machmakin.tsx
  app/main/stats.tsx
  types/navigation.ts
Labels: ui-ux-improvement, component-architecture, responsive-design

#40 Feat/auto code fill
  app/auth/OTPverify.tsx
  app/auth/SignIn.tsx
  lib/env.ts
  package-lock.json
  package.json
  store/index.ts
Labels: ui-ux-improvement, accessibility-enhancement

#49 Feat/cloudinary
  app/main/index.tsx
  app/main/machmakin.tsx
  app/settings/SettingsScreen.tsx
  constants/colors.ts
  lib/storage.ts
  package-lock.json
  package.json
  postcss.config.js
  store/authSlice.ts
Labels: ui-ux-improvement, component-architecture
